version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    ports:
      - 8000:8000 
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prueba
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
